// Code generated by go-swagger; DO NOT EDIT.

package applications

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"washbonus/openapi/admin/models"
)

// GetAdminApplicationsOKCode is the HTTP code returned for type GetAdminApplicationsOK
const GetAdminApplicationsOKCode int = 200

/*GetAdminApplicationsOK OK

swagger:response getAdminApplicationsOK
*/
type GetAdminApplicationsOK struct {

	/*
	  In: Body
	*/
	Payload *GetAdminApplicationsOKBody `json:"body,omitempty"`
}

// NewGetAdminApplicationsOK creates GetAdminApplicationsOK with default headers values
func NewGetAdminApplicationsOK() *GetAdminApplicationsOK {

	return &GetAdminApplicationsOK{}
}

// WithPayload adds the payload to the get admin applications o k response
func (o *GetAdminApplicationsOK) WithPayload(payload *GetAdminApplicationsOKBody) *GetAdminApplicationsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get admin applications o k response
func (o *GetAdminApplicationsOK) SetPayload(payload *GetAdminApplicationsOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAdminApplicationsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

func (o *GetAdminApplicationsOK) GetAdminApplicationsResponder() {}

/*GetAdminApplicationsDefault Generic error response

swagger:response getAdminApplicationsDefault
*/
type GetAdminApplicationsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetAdminApplicationsDefault creates GetAdminApplicationsDefault with default headers values
func NewGetAdminApplicationsDefault(code int) *GetAdminApplicationsDefault {
	if code <= 0 {
		code = 500
	}

	return &GetAdminApplicationsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get admin applications default response
func (o *GetAdminApplicationsDefault) WithStatusCode(code int) *GetAdminApplicationsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get admin applications default response
func (o *GetAdminApplicationsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get admin applications default response
func (o *GetAdminApplicationsDefault) WithPayload(payload *models.Error) *GetAdminApplicationsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get admin applications default response
func (o *GetAdminApplicationsDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAdminApplicationsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

func (o *GetAdminApplicationsDefault) GetAdminApplicationsResponder() {}

type GetAdminApplicationsNotImplementedResponder struct {
	middleware.Responder
}

func (*GetAdminApplicationsNotImplementedResponder) GetAdminApplicationsResponder() {}

func GetAdminApplicationsNotImplemented() GetAdminApplicationsResponder {
	return &GetAdminApplicationsNotImplementedResponder{
		middleware.NotImplemented(
			"operation authentication.GetAdminApplications has not yet been implemented",
		),
	}
}

type GetAdminApplicationsResponder interface {
	middleware.Responder
	GetAdminApplicationsResponder()
}
