// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"washbonus/openapi/admin/models"
)

// BlockAdminUserReader is a Reader for the BlockAdminUser structure.
type BlockAdminUserReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *BlockAdminUserReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewBlockAdminUserNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewBlockAdminUserDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewBlockAdminUserNoContent creates a BlockAdminUserNoContent with default headers values
func NewBlockAdminUserNoContent() *BlockAdminUserNoContent {
	return &BlockAdminUserNoContent{}
}

/*
BlockAdminUserNoContent describes a response with status code 204, with default header values.

OK
*/
type BlockAdminUserNoContent struct {
}

// IsSuccess returns true when this block admin user no content response has a 2xx status code
func (o *BlockAdminUserNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this block admin user no content response has a 3xx status code
func (o *BlockAdminUserNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this block admin user no content response has a 4xx status code
func (o *BlockAdminUserNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this block admin user no content response has a 5xx status code
func (o *BlockAdminUserNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this block admin user no content response a status code equal to that given
func (o *BlockAdminUserNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the block admin user no content response
func (o *BlockAdminUserNoContent) Code() int {
	return 204
}

func (o *BlockAdminUserNoContent) Error() string {
	return fmt.Sprintf("[DELETE /users/{userId}][%d] blockAdminUserNoContent ", 204)
}

func (o *BlockAdminUserNoContent) String() string {
	return fmt.Sprintf("[DELETE /users/{userId}][%d] blockAdminUserNoContent ", 204)
}

func (o *BlockAdminUserNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewBlockAdminUserDefault creates a BlockAdminUserDefault with default headers values
func NewBlockAdminUserDefault(code int) *BlockAdminUserDefault {
	return &BlockAdminUserDefault{
		_statusCode: code,
	}
}

/*
BlockAdminUserDefault describes a response with status code -1, with default header values.

Generic error response
*/
type BlockAdminUserDefault struct {
	_statusCode int

	Payload *models.Error
}

// IsSuccess returns true when this block admin user default response has a 2xx status code
func (o *BlockAdminUserDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this block admin user default response has a 3xx status code
func (o *BlockAdminUserDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this block admin user default response has a 4xx status code
func (o *BlockAdminUserDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this block admin user default response has a 5xx status code
func (o *BlockAdminUserDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this block admin user default response a status code equal to that given
func (o *BlockAdminUserDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the block admin user default response
func (o *BlockAdminUserDefault) Code() int {
	return o._statusCode
}

func (o *BlockAdminUserDefault) Error() string {
	return fmt.Sprintf("[DELETE /users/{userId}][%d] blockAdminUser default  %+v", o._statusCode, o.Payload)
}

func (o *BlockAdminUserDefault) String() string {
	return fmt.Sprintf("[DELETE /users/{userId}][%d] blockAdminUser default  %+v", o._statusCode, o.Payload)
}

func (o *BlockAdminUserDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *BlockAdminUserDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
