#!/bin/bash

rm -r ./certs
mkdir ./certs

# 1. Generate CA's private key and self-signed certificate
openssl req -addext "subjectAltName = DNS:localhost" -x509 -newkey rsa:4096 -days 365 -nodes -keyout certs/dev-ca-key.pem -out certs/dev-ca-cert.pem -subj "/C=RU/ST=./L=./O=./OU=./CN=localhost/emailAddress=."
echo "CA's self-signed certificate"
openssl x509 -in certs/ca-cert.pem -noout -text

# 2. Generate web server's private key and certificate signing request (CSR)
openssl req  -addext "subjectAltName = DNS:localhost" -newkey rsa:4096 -nodes -keyout certs/dev-server-key.pem -out certs/dev-server-req.pem -subj "/C=RU/ST=./L=./O=./OU=./CN=localhost/emailAddress=."

# 3. Use CA's private key to sign web server's CSR and get back the signed certificate
openssl x509 -req -in certs/dev-server-req.pem -days 60 -CA certs/dev-ca-cert.pem -CAkey certs/dev-ca-key.pem -CAcreateserial -out certs/dev-server-cert.pem
echo "Server's signed certificate"
openssl x509 -in certs/dev-server-cert.pem -noout -text

# 4. RSA for JWT
openssl genrsa -out certs/wash-server-rsa-keyfile 1024
openssl rsa -in certs/wash-server-rsa-keyfile -pubout -out certs/wash-server-rsa-keyfile.pub
