#!/bin/bash
# Swagger API generate

if ! [ -x "$(command -v docker)" ]; then
  echo 'Error: "docker" is not installed.' >&2
  exit 1
fi

set -x -e -o pipefail

rm -rf ./transport/rest/restapi/restapi/operations/balance
mkdir ./transport/rest/restapi/restapi/operations/balance

shopt -s expand_aliases
alias swagger="docker run --rm -it -e GOPATH=$HOME/go:/go -v $HOME:$HOME -w $(pwd) quay.io/goswagger/swagger"
swagger generate server -t ./transport/rest/restapi -f ./swagger.yaml --exclude-main
swagger generate client -t ./transport/rest/restapi -f ./swagger.yaml
sudo chown -R "$USER:$USER" ./rest/restapi/*
