#!/bin/bash
# GRPC generate

protoc --go_out=./internal/transport/grpc --go_opt=paths=source_relative --go-grpc_out=./internal/transport/grpc --go-grpc_opt=paths=source_relative ./internal/transport/grpc/grpc.proto
