swagger: "2.0"
info:
  title: Rabbit-intAPI
  description: Rabbit internal httpAPI
  version: 1.0.0
host: localhost:15762
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  Auth:
    description: internal auth
    type: basic
security:
  - Auth: []

schemes:
  - https
paths:
  /api/users/{user_id}:
    put:
      operationId: createUser
      description: create rabbit user
      security:
        - Auth: [ ]
      parameters:
        - in: path
          name: user_id
          required: true
          type: string
        - in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/CreateUser"
      responses:
        201:
          description: Created
        204:
          description: ok
        400:
          description: bad request
        500:
          description: error
    delete:
      operationId: deleteUser
      description: delete rabbit user
      security:
        - Auth: []
      parameters:
        - in: path
          name: user_id
          required: true
          type: string
      responses:
        204:
          description: ok
        400:
          description: bad request
        500:
          description: error
  /api/permissions/{vhost}/{user_id}:
    put:
      operationId: setUserPerms
      description: set rabbit user permissions
      security:
        - Auth: [ ]
      parameters:
        - in: path
          name: vhost
          required: true
          type: string
        - in: path
          name: user_id
          required: true
          type: string
        - in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/ManagePermissions"
      responses:
        201:
          description: ok
        204:
          description: ok
        400:
          description: bad request
        500:
          description: error
definitions:
  CreateUser:
    type: object
    properties:
      password:
        type: string
      tags:
        type: string
    required:
      - tags
      - password
  ManagePermissions:
    type: object
    properties:
      configure:
        type: string
      write:
        type: string
      read:
        type: string
