// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"wash-bonus/internal/api/restapi/models"
)

// EditUserReader is a Reader for the EditUser structure.
type EditUserReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EditUserReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewEditUserOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewEditUserDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewEditUserOK creates a EditUserOK with default headers values
func NewEditUserOK() *EditUserOK {
	return &EditUserOK{}
}

/*
EditUserOK describes a response with status code 200, with default header values.

OK
*/
type EditUserOK struct {
}

// IsSuccess returns true when this edit user o k response has a 2xx status code
func (o *EditUserOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this edit user o k response has a 3xx status code
func (o *EditUserOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this edit user o k response has a 4xx status code
func (o *EditUserOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this edit user o k response has a 5xx status code
func (o *EditUserOK) IsServerError() bool {
	return false
}

// IsCode returns true when this edit user o k response a status code equal to that given
func (o *EditUserOK) IsCode(code int) bool {
	return code == 200
}

func (o *EditUserOK) Error() string {
	return fmt.Sprintf("[PUT /user/edit][%d] editUserOK ", 200)
}

func (o *EditUserOK) String() string {
	return fmt.Sprintf("[PUT /user/edit][%d] editUserOK ", 200)
}

func (o *EditUserOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewEditUserDefault creates a EditUserDefault with default headers values
func NewEditUserDefault(code int) *EditUserDefault {
	return &EditUserDefault{
		_statusCode: code,
	}
}

/*
EditUserDefault describes a response with status code -1, with default header values.

error
*/
type EditUserDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the edit user default response
func (o *EditUserDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this edit user default response has a 2xx status code
func (o *EditUserDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this edit user default response has a 3xx status code
func (o *EditUserDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this edit user default response has a 4xx status code
func (o *EditUserDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this edit user default response has a 5xx status code
func (o *EditUserDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this edit user default response a status code equal to that given
func (o *EditUserDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *EditUserDefault) Error() string {
	return fmt.Sprintf("[PUT /user/edit][%d] editUser default  %+v", o._statusCode, o.Payload)
}

func (o *EditUserDefault) String() string {
	return fmt.Sprintf("[PUT /user/edit][%d] editUser default  %+v", o._statusCode, o.Payload)
}

func (o *EditUserDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *EditUserDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
EditUserBody edit user body
swagger:model EditUserBody
*/
type EditUserBody struct {

	// data
	Data *models.UserAdd `json:"data,omitempty"`

	// id
	ID string `json:"id,omitempty"`
}

// Validate validates this edit user body
func (o *EditUserBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *EditUserBody) validateData(formats strfmt.Registry) error {
	if swag.IsZero(o.Data) { // not required
		return nil
	}

	if o.Data != nil {
		if err := o.Data.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("body" + "." + "data")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("body" + "." + "data")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this edit user body based on the context it is used
func (o *EditUserBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *EditUserBody) contextValidateData(ctx context.Context, formats strfmt.Registry) error {

	if o.Data != nil {
		if err := o.Data.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("body" + "." + "data")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("body" + "." + "data")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *EditUserBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *EditUserBody) UnmarshalBinary(b []byte) error {
	var res EditUserBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
