// Code generated by go-swagger; DO NOT EDIT.

package bonus

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"wash_bonus/openapi/models"
)

// NewUseParams creates a new UseParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUseParams() *UseParams {
	return &UseParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUseParamsWithTimeout creates a new UseParams object
// with the ability to set a timeout on a request.
func NewUseParamsWithTimeout(timeout time.Duration) *UseParams {
	return &UseParams{
		timeout: timeout,
	}
}

// NewUseParamsWithContext creates a new UseParams object
// with the ability to set a context for a request.
func NewUseParamsWithContext(ctx context.Context) *UseParams {
	return &UseParams{
		Context: ctx,
	}
}

// NewUseParamsWithHTTPClient creates a new UseParams object
// with the ability to set a custom HTTPClient for a request.
func NewUseParamsWithHTTPClient(client *http.Client) *UseParams {
	return &UseParams{
		HTTPClient: client,
	}
}

/*
UseParams contains all the parameters to send to the API endpoint

	for the use operation.

	Typically these are written to a http.Request.
*/
type UseParams struct {

	// Body.
	Body *models.BonusConsume

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the use params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UseParams) WithDefaults() *UseParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the use params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UseParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the use params
func (o *UseParams) WithTimeout(timeout time.Duration) *UseParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the use params
func (o *UseParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the use params
func (o *UseParams) WithContext(ctx context.Context) *UseParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the use params
func (o *UseParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the use params
func (o *UseParams) WithHTTPClient(client *http.Client) *UseParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the use params
func (o *UseParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the use params
func (o *UseParams) WithBody(body *models.BonusConsume) *UseParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the use params
func (o *UseParams) SetBody(body *models.BonusConsume) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *UseParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
