// Code generated by go-swagger; DO NOT EDIT.

package wash_server

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"wash-bonus/transport/rest/restapi/models"
)

// GenerateKeyWashServerReader is a Reader for the GenerateKeyWashServer structure.
type GenerateKeyWashServerReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GenerateKeyWashServerReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGenerateKeyWashServerOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGenerateKeyWashServerDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGenerateKeyWashServerOK creates a GenerateKeyWashServerOK with default headers values
func NewGenerateKeyWashServerOK() *GenerateKeyWashServerOK {
	return &GenerateKeyWashServerOK{}
}

/*
GenerateKeyWashServerOK describes a response with status code 200, with default header values.

OK
*/
type GenerateKeyWashServerOK struct {
	Payload *models.WashServerGenerateKeyResp
}

// IsSuccess returns true when this generate key wash server o k response has a 2xx status code
func (o *GenerateKeyWashServerOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this generate key wash server o k response has a 3xx status code
func (o *GenerateKeyWashServerOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this generate key wash server o k response has a 4xx status code
func (o *GenerateKeyWashServerOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this generate key wash server o k response has a 5xx status code
func (o *GenerateKeyWashServerOK) IsServerError() bool {
	return false
}

// IsCode returns true when this generate key wash server o k response a status code equal to that given
func (o *GenerateKeyWashServerOK) IsCode(code int) bool {
	return code == 200
}

func (o *GenerateKeyWashServerOK) Error() string {
	return fmt.Sprintf("[PUT /washServer/{id}/generate-key][%d] generateKeyWashServerOK  %+v", 200, o.Payload)
}

func (o *GenerateKeyWashServerOK) String() string {
	return fmt.Sprintf("[PUT /washServer/{id}/generate-key][%d] generateKeyWashServerOK  %+v", 200, o.Payload)
}

func (o *GenerateKeyWashServerOK) GetPayload() *models.WashServerGenerateKeyResp {
	return o.Payload
}

func (o *GenerateKeyWashServerOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.WashServerGenerateKeyResp)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGenerateKeyWashServerDefault creates a GenerateKeyWashServerDefault with default headers values
func NewGenerateKeyWashServerDefault(code int) *GenerateKeyWashServerDefault {
	return &GenerateKeyWashServerDefault{
		_statusCode: code,
	}
}

/*
GenerateKeyWashServerDefault describes a response with status code -1, with default header values.

error
*/
type GenerateKeyWashServerDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the generate key wash server default response
func (o *GenerateKeyWashServerDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this generate key wash server default response has a 2xx status code
func (o *GenerateKeyWashServerDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this generate key wash server default response has a 3xx status code
func (o *GenerateKeyWashServerDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this generate key wash server default response has a 4xx status code
func (o *GenerateKeyWashServerDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this generate key wash server default response has a 5xx status code
func (o *GenerateKeyWashServerDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this generate key wash server default response a status code equal to that given
func (o *GenerateKeyWashServerDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *GenerateKeyWashServerDefault) Error() string {
	return fmt.Sprintf("[PUT /washServer/{id}/generate-key][%d] generateKeyWashServer default  %+v", o._statusCode, o.Payload)
}

func (o *GenerateKeyWashServerDefault) String() string {
	return fmt.Sprintf("[PUT /washServer/{id}/generate-key][%d] generateKeyWashServer default  %+v", o._statusCode, o.Payload)
}

func (o *GenerateKeyWashServerDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *GenerateKeyWashServerDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
