// Code generated by go-swagger; DO NOT EDIT.

package wash_server

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"wash-bonus/transport/rest/restapi/models"
)

// NewListWashServerParams creates a new ListWashServerParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListWashServerParams() *ListWashServerParams {
	return &ListWashServerParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListWashServerParamsWithTimeout creates a new ListWashServerParams object
// with the ability to set a timeout on a request.
func NewListWashServerParamsWithTimeout(timeout time.Duration) *ListWashServerParams {
	return &ListWashServerParams{
		timeout: timeout,
	}
}

// NewListWashServerParamsWithContext creates a new ListWashServerParams object
// with the ability to set a context for a request.
func NewListWashServerParamsWithContext(ctx context.Context) *ListWashServerParams {
	return &ListWashServerParams{
		Context: ctx,
	}
}

// NewListWashServerParamsWithHTTPClient creates a new ListWashServerParams object
// with the ability to set a custom HTTPClient for a request.
func NewListWashServerParamsWithHTTPClient(client *http.Client) *ListWashServerParams {
	return &ListWashServerParams{
		HTTPClient: client,
	}
}

/*
ListWashServerParams contains all the parameters to send to the API endpoint

	for the list wash server operation.

	Typically these are written to a http.Request.
*/
type ListWashServerParams struct {

	// Body.
	Body *models.ListParams

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list wash server params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListWashServerParams) WithDefaults() *ListWashServerParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list wash server params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListWashServerParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list wash server params
func (o *ListWashServerParams) WithTimeout(timeout time.Duration) *ListWashServerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list wash server params
func (o *ListWashServerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list wash server params
func (o *ListWashServerParams) WithContext(ctx context.Context) *ListWashServerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list wash server params
func (o *ListWashServerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list wash server params
func (o *ListWashServerParams) WithHTTPClient(client *http.Client) *ListWashServerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list wash server params
func (o *ListWashServerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the list wash server params
func (o *ListWashServerParams) WithBody(body *models.ListParams) *ListWashServerParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the list wash server params
func (o *ListWashServerParams) SetBody(body *models.ListParams) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *ListWashServerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
