// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PermissionAdd permission model for add and edit methods
//
// swagger:model permissionAdd
type PermissionAdd struct {

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this permission add
func (m *PermissionAdd) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this permission add based on context it is used
func (m *PermissionAdd) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PermissionAdd) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PermissionAdd) UnmarshalBinary(b []byte) error {
	var res PermissionAdd
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
