// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SessionAdd session model for add and edit methods
//
// swagger:model sessionAdd
type SessionAdd struct {

	// active
	Active bool `json:"active,omitempty"`

	// closing at
	// Format: date-time
	ClosingAt *strfmt.DateTime `json:"closingAt,omitempty"`

	// expiration at
	// Format: date-time
	ExpirationAt *strfmt.DateTime `json:"expirationAt,omitempty"`

	// update at
	// Format: date-time
	UpdateAt *strfmt.DateTime `json:"updateAt,omitempty"`

	// user
	User string `json:"user,omitempty"`
}

// Validate validates this session add
func (m *SessionAdd) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateClosingAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateExpirationAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUpdateAt(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SessionAdd) validateClosingAt(formats strfmt.Registry) error {
	if swag.IsZero(m.ClosingAt) { // not required
		return nil
	}

	if err := validate.FormatOf("closingAt", "body", "date-time", m.ClosingAt.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *SessionAdd) validateExpirationAt(formats strfmt.Registry) error {
	if swag.IsZero(m.ExpirationAt) { // not required
		return nil
	}

	if err := validate.FormatOf("expirationAt", "body", "date-time", m.ExpirationAt.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *SessionAdd) validateUpdateAt(formats strfmt.Registry) error {
	if swag.IsZero(m.UpdateAt) { // not required
		return nil
	}

	if err := validate.FormatOf("updateAt", "body", "date-time", m.UpdateAt.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this session add based on context it is used
func (m *SessionAdd) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SessionAdd) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SessionAdd) UnmarshalBinary(b []byte) error {
	var res SessionAdd
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
