// Code generated by go-swagger; DO NOT EDIT.

package wash_servers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"wash_admin/openapi/models"
)

// AddReader is a Reader for the Add structure.
type AddReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AddReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewAddNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewAddNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewAddInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewAddNoContent creates a AddNoContent with default headers values
func NewAddNoContent() *AddNoContent {
	return &AddNoContent{}
}

/*
AddNoContent describes a response with status code 204, with default header values.

Success creation
*/
type AddNoContent struct {
}

// IsSuccess returns true when this add no content response has a 2xx status code
func (o *AddNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this add no content response has a 3xx status code
func (o *AddNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this add no content response has a 4xx status code
func (o *AddNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this add no content response has a 5xx status code
func (o *AddNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this add no content response a status code equal to that given
func (o *AddNoContent) IsCode(code int) bool {
	return code == 204
}

func (o *AddNoContent) Error() string {
	return fmt.Sprintf("[PUT /wash-server][%d] addNoContent ", 204)
}

func (o *AddNoContent) String() string {
	return fmt.Sprintf("[PUT /wash-server][%d] addNoContent ", 204)
}

func (o *AddNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAddNotFound creates a AddNotFound with default headers values
func NewAddNotFound() *AddNotFound {
	return &AddNotFound{}
}

/*
AddNotFound describes a response with status code 404, with default header values.

WashServer not exists
*/
type AddNotFound struct {
	Payload *models.Error
}

// IsSuccess returns true when this add not found response has a 2xx status code
func (o *AddNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this add not found response has a 3xx status code
func (o *AddNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this add not found response has a 4xx status code
func (o *AddNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this add not found response has a 5xx status code
func (o *AddNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this add not found response a status code equal to that given
func (o *AddNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *AddNotFound) Error() string {
	return fmt.Sprintf("[PUT /wash-server][%d] addNotFound  %+v", 404, o.Payload)
}

func (o *AddNotFound) String() string {
	return fmt.Sprintf("[PUT /wash-server][%d] addNotFound  %+v", 404, o.Payload)
}

func (o *AddNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *AddNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAddInternalServerError creates a AddInternalServerError with default headers values
func NewAddInternalServerError() *AddInternalServerError {
	return &AddInternalServerError{}
}

/*
AddInternalServerError describes a response with status code 500, with default header values.

Internal error
*/
type AddInternalServerError struct {
	Payload *models.Error
}

// IsSuccess returns true when this add internal server error response has a 2xx status code
func (o *AddInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this add internal server error response has a 3xx status code
func (o *AddInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this add internal server error response has a 4xx status code
func (o *AddInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this add internal server error response has a 5xx status code
func (o *AddInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this add internal server error response a status code equal to that given
func (o *AddInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *AddInternalServerError) Error() string {
	return fmt.Sprintf("[PUT /wash-server][%d] addInternalServerError  %+v", 500, o.Payload)
}

func (o *AddInternalServerError) String() string {
	return fmt.Sprintf("[PUT /wash-server][%d] addInternalServerError  %+v", 500, o.Payload)
}

func (o *AddInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *AddInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
