// Code generated by go-swagger; DO NOT EDIT.

package applications

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new applications API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for applications API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	CreateAdminApplication(params *CreateAdminApplicationParams, opts ...ClientOption) (*CreateAdminApplicationOK, error)

	GetAdminApplicationByID(params *GetAdminApplicationByIDParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetAdminApplicationByIDOK, error)

	GetAdminApplications(params *GetAdminApplicationsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetAdminApplicationsOK, error)

	ReviewAdminApplication(params *ReviewAdminApplicationParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ReviewAdminApplicationNoContent, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
CreateAdminApplication create admin application API
*/
func (a *Client) CreateAdminApplication(params *CreateAdminApplicationParams, opts ...ClientOption) (*CreateAdminApplicationOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCreateAdminApplicationParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "createAdminApplication",
		Method:             "POST",
		PathPattern:        "/users/applications",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &CreateAdminApplicationReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*CreateAdminApplicationOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*CreateAdminApplicationDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
GetAdminApplicationByID get admin application by Id API
*/
func (a *Client) GetAdminApplicationByID(params *GetAdminApplicationByIDParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetAdminApplicationByIDOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetAdminApplicationByIDParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "getAdminApplicationById",
		Method:             "GET",
		PathPattern:        "/users/applications/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetAdminApplicationByIDReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetAdminApplicationByIDOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*GetAdminApplicationByIDDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
GetAdminApplications get admin applications API
*/
func (a *Client) GetAdminApplications(params *GetAdminApplicationsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetAdminApplicationsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetAdminApplicationsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "getAdminApplications",
		Method:             "GET",
		PathPattern:        "/users/applications",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetAdminApplicationsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetAdminApplicationsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*GetAdminApplicationsDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
ReviewAdminApplication review admin application API
*/
func (a *Client) ReviewAdminApplication(params *ReviewAdminApplicationParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ReviewAdminApplicationNoContent, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewReviewAdminApplicationParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "reviewAdminApplication",
		Method:             "POST",
		PathPattern:        "/users/applications/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &ReviewAdminApplicationReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ReviewAdminApplicationNoContent)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*ReviewAdminApplicationDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
