// Code generated by go-swagger; DO NOT EDIT.

package applications

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"washbonus/openapi/admin/models"
)

// CreateAdminApplicationReader is a Reader for the CreateAdminApplication structure.
type CreateAdminApplicationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateAdminApplicationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateAdminApplicationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewCreateAdminApplicationDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCreateAdminApplicationOK creates a CreateAdminApplicationOK with default headers values
func NewCreateAdminApplicationOK() *CreateAdminApplicationOK {
	return &CreateAdminApplicationOK{}
}

/*
CreateAdminApplicationOK describes a response with status code 200, with default header values.

OK
*/
type CreateAdminApplicationOK struct {
	Payload *models.AdminApplication
}

// IsSuccess returns true when this create admin application o k response has a 2xx status code
func (o *CreateAdminApplicationOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create admin application o k response has a 3xx status code
func (o *CreateAdminApplicationOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create admin application o k response has a 4xx status code
func (o *CreateAdminApplicationOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this create admin application o k response has a 5xx status code
func (o *CreateAdminApplicationOK) IsServerError() bool {
	return false
}

// IsCode returns true when this create admin application o k response a status code equal to that given
func (o *CreateAdminApplicationOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the create admin application o k response
func (o *CreateAdminApplicationOK) Code() int {
	return 200
}

func (o *CreateAdminApplicationOK) Error() string {
	return fmt.Sprintf("[POST /users/applications][%d] createAdminApplicationOK  %+v", 200, o.Payload)
}

func (o *CreateAdminApplicationOK) String() string {
	return fmt.Sprintf("[POST /users/applications][%d] createAdminApplicationOK  %+v", 200, o.Payload)
}

func (o *CreateAdminApplicationOK) GetPayload() *models.AdminApplication {
	return o.Payload
}

func (o *CreateAdminApplicationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AdminApplication)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateAdminApplicationDefault creates a CreateAdminApplicationDefault with default headers values
func NewCreateAdminApplicationDefault(code int) *CreateAdminApplicationDefault {
	return &CreateAdminApplicationDefault{
		_statusCode: code,
	}
}

/*
CreateAdminApplicationDefault describes a response with status code -1, with default header values.

Generic error response
*/
type CreateAdminApplicationDefault struct {
	_statusCode int

	Payload *models.Error
}

// IsSuccess returns true when this create admin application default response has a 2xx status code
func (o *CreateAdminApplicationDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this create admin application default response has a 3xx status code
func (o *CreateAdminApplicationDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this create admin application default response has a 4xx status code
func (o *CreateAdminApplicationDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this create admin application default response has a 5xx status code
func (o *CreateAdminApplicationDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this create admin application default response a status code equal to that given
func (o *CreateAdminApplicationDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the create admin application default response
func (o *CreateAdminApplicationDefault) Code() int {
	return o._statusCode
}

func (o *CreateAdminApplicationDefault) Error() string {
	return fmt.Sprintf("[POST /users/applications][%d] createAdminApplication default  %+v", o._statusCode, o.Payload)
}

func (o *CreateAdminApplicationDefault) String() string {
	return fmt.Sprintf("[POST /users/applications][%d] createAdminApplication default  %+v", o._statusCode, o.Payload)
}

func (o *CreateAdminApplicationDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *CreateAdminApplicationDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
CreateAdminApplicationBody create admin application body
swagger:model CreateAdminApplicationBody
*/
type CreateAdminApplicationBody struct {

	// application
	Application *models.AdminApplicationCreation `json:"application,omitempty"`
}

// UnmarshalJSON unmarshals this object while disallowing additional properties from JSON
func (o *CreateAdminApplicationBody) UnmarshalJSON(data []byte) error {
	var props struct {

		// application
		Application *models.AdminApplicationCreation `json:"application,omitempty"`
	}

	dec := json.NewDecoder(bytes.NewReader(data))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&props); err != nil {
		return err
	}

	o.Application = props.Application
	return nil
}

// Validate validates this create admin application body
func (o *CreateAdminApplicationBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateApplication(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *CreateAdminApplicationBody) validateApplication(formats strfmt.Registry) error {
	if swag.IsZero(o.Application) { // not required
		return nil
	}

	if o.Application != nil {
		if err := o.Application.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("body" + "." + "application")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("body" + "." + "application")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this create admin application body based on the context it is used
func (o *CreateAdminApplicationBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateApplication(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *CreateAdminApplicationBody) contextValidateApplication(ctx context.Context, formats strfmt.Registry) error {

	if o.Application != nil {

		if swag.IsZero(o.Application) { // not required
			return nil
		}

		if err := o.Application.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("body" + "." + "application")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("body" + "." + "application")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *CreateAdminApplicationBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CreateAdminApplicationBody) UnmarshalBinary(b []byte) error {
	var res CreateAdminApplicationBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
