// Code generated by go-swagger; DO NOT EDIT.

package applications

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAdminApplicationByIDParams creates a new GetAdminApplicationByIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAdminApplicationByIDParams() *GetAdminApplicationByIDParams {
	return &GetAdminApplicationByIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAdminApplicationByIDParamsWithTimeout creates a new GetAdminApplicationByIDParams object
// with the ability to set a timeout on a request.
func NewGetAdminApplicationByIDParamsWithTimeout(timeout time.Duration) *GetAdminApplicationByIDParams {
	return &GetAdminApplicationByIDParams{
		timeout: timeout,
	}
}

// NewGetAdminApplicationByIDParamsWithContext creates a new GetAdminApplicationByIDParams object
// with the ability to set a context for a request.
func NewGetAdminApplicationByIDParamsWithContext(ctx context.Context) *GetAdminApplicationByIDParams {
	return &GetAdminApplicationByIDParams{
		Context: ctx,
	}
}

// NewGetAdminApplicationByIDParamsWithHTTPClient creates a new GetAdminApplicationByIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAdminApplicationByIDParamsWithHTTPClient(client *http.Client) *GetAdminApplicationByIDParams {
	return &GetAdminApplicationByIDParams{
		HTTPClient: client,
	}
}

/*
GetAdminApplicationByIDParams contains all the parameters to send to the API endpoint

	for the get admin application by Id operation.

	Typically these are written to a http.Request.
*/
type GetAdminApplicationByIDParams struct {

	// ID.
	//
	// Format: uuid
	ID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get admin application by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAdminApplicationByIDParams) WithDefaults() *GetAdminApplicationByIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get admin application by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAdminApplicationByIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get admin application by Id params
func (o *GetAdminApplicationByIDParams) WithTimeout(timeout time.Duration) *GetAdminApplicationByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get admin application by Id params
func (o *GetAdminApplicationByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get admin application by Id params
func (o *GetAdminApplicationByIDParams) WithContext(ctx context.Context) *GetAdminApplicationByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get admin application by Id params
func (o *GetAdminApplicationByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get admin application by Id params
func (o *GetAdminApplicationByIDParams) WithHTTPClient(client *http.Client) *GetAdminApplicationByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get admin application by Id params
func (o *GetAdminApplicationByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get admin application by Id params
func (o *GetAdminApplicationByIDParams) WithID(id strfmt.UUID) *GetAdminApplicationByIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get admin application by Id params
func (o *GetAdminApplicationByIDParams) SetID(id strfmt.UUID) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetAdminApplicationByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
