// Code generated by go-swagger; DO NOT EDIT.

package applications

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"washbonus/openapi/admin/models"
)

// GetAdminApplicationByIDReader is a Reader for the GetAdminApplicationByID structure.
type GetAdminApplicationByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAdminApplicationByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAdminApplicationByIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetAdminApplicationByIDDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetAdminApplicationByIDOK creates a GetAdminApplicationByIDOK with default headers values
func NewGetAdminApplicationByIDOK() *GetAdminApplicationByIDOK {
	return &GetAdminApplicationByIDOK{}
}

/*
GetAdminApplicationByIDOK describes a response with status code 200, with default header values.

OK
*/
type GetAdminApplicationByIDOK struct {
	Payload *models.AdminApplication
}

// IsSuccess returns true when this get admin application by Id o k response has a 2xx status code
func (o *GetAdminApplicationByIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get admin application by Id o k response has a 3xx status code
func (o *GetAdminApplicationByIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get admin application by Id o k response has a 4xx status code
func (o *GetAdminApplicationByIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get admin application by Id o k response has a 5xx status code
func (o *GetAdminApplicationByIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get admin application by Id o k response a status code equal to that given
func (o *GetAdminApplicationByIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get admin application by Id o k response
func (o *GetAdminApplicationByIDOK) Code() int {
	return 200
}

func (o *GetAdminApplicationByIDOK) Error() string {
	return fmt.Sprintf("[GET /users/applications/{id}][%d] getAdminApplicationByIdOK  %+v", 200, o.Payload)
}

func (o *GetAdminApplicationByIDOK) String() string {
	return fmt.Sprintf("[GET /users/applications/{id}][%d] getAdminApplicationByIdOK  %+v", 200, o.Payload)
}

func (o *GetAdminApplicationByIDOK) GetPayload() *models.AdminApplication {
	return o.Payload
}

func (o *GetAdminApplicationByIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AdminApplication)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAdminApplicationByIDDefault creates a GetAdminApplicationByIDDefault with default headers values
func NewGetAdminApplicationByIDDefault(code int) *GetAdminApplicationByIDDefault {
	return &GetAdminApplicationByIDDefault{
		_statusCode: code,
	}
}

/*
GetAdminApplicationByIDDefault describes a response with status code -1, with default header values.

Generic error response
*/
type GetAdminApplicationByIDDefault struct {
	_statusCode int

	Payload *models.Error
}

// IsSuccess returns true when this get admin application by Id default response has a 2xx status code
func (o *GetAdminApplicationByIDDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get admin application by Id default response has a 3xx status code
func (o *GetAdminApplicationByIDDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get admin application by Id default response has a 4xx status code
func (o *GetAdminApplicationByIDDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get admin application by Id default response has a 5xx status code
func (o *GetAdminApplicationByIDDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get admin application by Id default response a status code equal to that given
func (o *GetAdminApplicationByIDDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get admin application by Id default response
func (o *GetAdminApplicationByIDDefault) Code() int {
	return o._statusCode
}

func (o *GetAdminApplicationByIDDefault) Error() string {
	return fmt.Sprintf("[GET /users/applications/{id}][%d] getAdminApplicationById default  %+v", o._statusCode, o.Payload)
}

func (o *GetAdminApplicationByIDDefault) String() string {
	return fmt.Sprintf("[GET /users/applications/{id}][%d] getAdminApplicationById default  %+v", o._statusCode, o.Payload)
}

func (o *GetAdminApplicationByIDDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetAdminApplicationByIDDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
