// Code generated by go-swagger; DO NOT EDIT.

package server_groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"washbonus/openapi/admin/models"
)

// CreateServerGroupReader is a Reader for the CreateServerGroup structure.
type CreateServerGroupReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateServerGroupReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateServerGroupOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewCreateServerGroupDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCreateServerGroupOK creates a CreateServerGroupOK with default headers values
func NewCreateServerGroupOK() *CreateServerGroupOK {
	return &CreateServerGroupOK{}
}

/*
CreateServerGroupOK describes a response with status code 200, with default header values.

Successfull created
*/
type CreateServerGroupOK struct {
	Payload *models.ServerGroup
}

// IsSuccess returns true when this create server group o k response has a 2xx status code
func (o *CreateServerGroupOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create server group o k response has a 3xx status code
func (o *CreateServerGroupOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create server group o k response has a 4xx status code
func (o *CreateServerGroupOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this create server group o k response has a 5xx status code
func (o *CreateServerGroupOK) IsServerError() bool {
	return false
}

// IsCode returns true when this create server group o k response a status code equal to that given
func (o *CreateServerGroupOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the create server group o k response
func (o *CreateServerGroupOK) Code() int {
	return 200
}

func (o *CreateServerGroupOK) Error() string {
	return fmt.Sprintf("[POST /server-groups][%d] createServerGroupOK  %+v", 200, o.Payload)
}

func (o *CreateServerGroupOK) String() string {
	return fmt.Sprintf("[POST /server-groups][%d] createServerGroupOK  %+v", 200, o.Payload)
}

func (o *CreateServerGroupOK) GetPayload() *models.ServerGroup {
	return o.Payload
}

func (o *CreateServerGroupOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServerGroup)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateServerGroupDefault creates a CreateServerGroupDefault with default headers values
func NewCreateServerGroupDefault(code int) *CreateServerGroupDefault {
	return &CreateServerGroupDefault{
		_statusCode: code,
	}
}

/*
CreateServerGroupDefault describes a response with status code -1, with default header values.

Generic error response
*/
type CreateServerGroupDefault struct {
	_statusCode int

	Payload *models.Error
}

// IsSuccess returns true when this create server group default response has a 2xx status code
func (o *CreateServerGroupDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this create server group default response has a 3xx status code
func (o *CreateServerGroupDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this create server group default response has a 4xx status code
func (o *CreateServerGroupDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this create server group default response has a 5xx status code
func (o *CreateServerGroupDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this create server group default response a status code equal to that given
func (o *CreateServerGroupDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the create server group default response
func (o *CreateServerGroupDefault) Code() int {
	return o._statusCode
}

func (o *CreateServerGroupDefault) Error() string {
	return fmt.Sprintf("[POST /server-groups][%d] createServerGroup default  %+v", o._statusCode, o.Payload)
}

func (o *CreateServerGroupDefault) String() string {
	return fmt.Sprintf("[POST /server-groups][%d] createServerGroup default  %+v", o._statusCode, o.Payload)
}

func (o *CreateServerGroupDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *CreateServerGroupDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
