// Code generated by go-swagger; DO NOT EDIT.

package server_groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"washbonus/openapi/admin/models"
)

// UpdateServerGroupReader is a Reader for the UpdateServerGroup structure.
type UpdateServerGroupReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateServerGroupReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateServerGroupOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewUpdateServerGroupDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewUpdateServerGroupOK creates a UpdateServerGroupOK with default headers values
func NewUpdateServerGroupOK() *UpdateServerGroupOK {
	return &UpdateServerGroupOK{}
}

/*
UpdateServerGroupOK describes a response with status code 200, with default header values.

Successfull updated
*/
type UpdateServerGroupOK struct {
	Payload *models.ServerGroup
}

// IsSuccess returns true when this update server group o k response has a 2xx status code
func (o *UpdateServerGroupOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this update server group o k response has a 3xx status code
func (o *UpdateServerGroupOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update server group o k response has a 4xx status code
func (o *UpdateServerGroupOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this update server group o k response has a 5xx status code
func (o *UpdateServerGroupOK) IsServerError() bool {
	return false
}

// IsCode returns true when this update server group o k response a status code equal to that given
func (o *UpdateServerGroupOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the update server group o k response
func (o *UpdateServerGroupOK) Code() int {
	return 200
}

func (o *UpdateServerGroupOK) Error() string {
	return fmt.Sprintf("[PATCH /server-groups/{groupId}][%d] updateServerGroupOK  %+v", 200, o.Payload)
}

func (o *UpdateServerGroupOK) String() string {
	return fmt.Sprintf("[PATCH /server-groups/{groupId}][%d] updateServerGroupOK  %+v", 200, o.Payload)
}

func (o *UpdateServerGroupOK) GetPayload() *models.ServerGroup {
	return o.Payload
}

func (o *UpdateServerGroupOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServerGroup)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateServerGroupDefault creates a UpdateServerGroupDefault with default headers values
func NewUpdateServerGroupDefault(code int) *UpdateServerGroupDefault {
	return &UpdateServerGroupDefault{
		_statusCode: code,
	}
}

/*
UpdateServerGroupDefault describes a response with status code -1, with default header values.

Generic error response
*/
type UpdateServerGroupDefault struct {
	_statusCode int

	Payload *models.Error
}

// IsSuccess returns true when this update server group default response has a 2xx status code
func (o *UpdateServerGroupDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this update server group default response has a 3xx status code
func (o *UpdateServerGroupDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this update server group default response has a 4xx status code
func (o *UpdateServerGroupDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this update server group default response has a 5xx status code
func (o *UpdateServerGroupDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this update server group default response a status code equal to that given
func (o *UpdateServerGroupDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the update server group default response
func (o *UpdateServerGroupDefault) Code() int {
	return o._statusCode
}

func (o *UpdateServerGroupDefault) Error() string {
	return fmt.Sprintf("[PATCH /server-groups/{groupId}][%d] updateServerGroup default  %+v", o._statusCode, o.Payload)
}

func (o *UpdateServerGroupDefault) String() string {
	return fmt.Sprintf("[PATCH /server-groups/{groupId}][%d] updateServerGroup default  %+v", o._statusCode, o.Payload)
}

func (o *UpdateServerGroupDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *UpdateServerGroupDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
