// Code generated by go-swagger; DO NOT EDIT.

package wash_servers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"washBonus/openapi/models"
)

// DeleteWashServerNoContentCode is the HTTP code returned for type DeleteWashServerNoContent
const DeleteWashServerNoContentCode int = 204

/*
DeleteWashServerNoContent OK

swagger:response deleteWashServerNoContent
*/
type DeleteWashServerNoContent struct {
}

// NewDeleteWashServerNoContent creates DeleteWashServerNoContent with default headers values
func NewDeleteWashServerNoContent() *DeleteWashServerNoContent {

	return &DeleteWashServerNoContent{}
}

// WriteResponse to the client
func (o *DeleteWashServerNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

func (o *DeleteWashServerNoContent) DeleteWashServerResponder() {}

// DeleteWashServerBadRequestCode is the HTTP code returned for type DeleteWashServerBadRequest
const DeleteWashServerBadRequestCode int = 400

/*
DeleteWashServerBadRequest Bad request

swagger:response deleteWashServerBadRequest
*/
type DeleteWashServerBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteWashServerBadRequest creates DeleteWashServerBadRequest with default headers values
func NewDeleteWashServerBadRequest() *DeleteWashServerBadRequest {

	return &DeleteWashServerBadRequest{}
}

// WithPayload adds the payload to the delete wash server bad request response
func (o *DeleteWashServerBadRequest) WithPayload(payload *models.Error) *DeleteWashServerBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete wash server bad request response
func (o *DeleteWashServerBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteWashServerBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

func (o *DeleteWashServerBadRequest) DeleteWashServerResponder() {}

// DeleteWashServerForbiddenCode is the HTTP code returned for type DeleteWashServerForbidden
const DeleteWashServerForbiddenCode int = 403

/*
DeleteWashServerForbidden Forbidden

swagger:response deleteWashServerForbidden
*/
type DeleteWashServerForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteWashServerForbidden creates DeleteWashServerForbidden with default headers values
func NewDeleteWashServerForbidden() *DeleteWashServerForbidden {

	return &DeleteWashServerForbidden{}
}

// WithPayload adds the payload to the delete wash server forbidden response
func (o *DeleteWashServerForbidden) WithPayload(payload *models.Error) *DeleteWashServerForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete wash server forbidden response
func (o *DeleteWashServerForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteWashServerForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

func (o *DeleteWashServerForbidden) DeleteWashServerResponder() {}

// DeleteWashServerNotFoundCode is the HTTP code returned for type DeleteWashServerNotFound
const DeleteWashServerNotFoundCode int = 404

/*
DeleteWashServerNotFound Not Found

swagger:response deleteWashServerNotFound
*/
type DeleteWashServerNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteWashServerNotFound creates DeleteWashServerNotFound with default headers values
func NewDeleteWashServerNotFound() *DeleteWashServerNotFound {

	return &DeleteWashServerNotFound{}
}

// WithPayload adds the payload to the delete wash server not found response
func (o *DeleteWashServerNotFound) WithPayload(payload *models.Error) *DeleteWashServerNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete wash server not found response
func (o *DeleteWashServerNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteWashServerNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

func (o *DeleteWashServerNotFound) DeleteWashServerResponder() {}

// DeleteWashServerInternalServerErrorCode is the HTTP code returned for type DeleteWashServerInternalServerError
const DeleteWashServerInternalServerErrorCode int = 500

/*
DeleteWashServerInternalServerError Internal error

swagger:response deleteWashServerInternalServerError
*/
type DeleteWashServerInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteWashServerInternalServerError creates DeleteWashServerInternalServerError with default headers values
func NewDeleteWashServerInternalServerError() *DeleteWashServerInternalServerError {

	return &DeleteWashServerInternalServerError{}
}

// WithPayload adds the payload to the delete wash server internal server error response
func (o *DeleteWashServerInternalServerError) WithPayload(payload *models.Error) *DeleteWashServerInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete wash server internal server error response
func (o *DeleteWashServerInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteWashServerInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

func (o *DeleteWashServerInternalServerError) DeleteWashServerResponder() {}

type DeleteWashServerNotImplementedResponder struct {
	middleware.Responder
}

func (*DeleteWashServerNotImplementedResponder) DeleteWashServerResponder() {}

func DeleteWashServerNotImplemented() DeleteWashServerResponder {
	return &DeleteWashServerNotImplementedResponder{
		middleware.NotImplemented(
			"operation authentication.DeleteWashServer has not yet been implemented",
		),
	}
}

type DeleteWashServerResponder interface {
	middleware.Responder
	DeleteWashServerResponder()
}
