// Code generated by mtgroup-generator.
package app

import (
	"github.com/go-openapi/strfmt"
	"time"

	"github.com/google/uuid"

	"wash-bonus/internal/app"
)

// Make sure not to overwrite this file after you generated it because all your edits would be lost!

var (
	isolatedEntityID = uuid.New().String()
	profileID        = uuid.New().String()
	profile          = app.Profile{
		ID:    profileID,
		Authn: true,
		Authz: app.Authz{
			User:    true,
			Admin:   true,
			Manager: true,
		},
		IsolatedEntityID: isolatedEntityID,
	}
	profileUnAuth = app.Profile{
		ID:    profileID,
		Authn: false,
		Authz: app.Authz{
			User:    false,
			Admin:   false,
			Manager: false,
		},
		IsolatedEntityID: isolatedEntityID,
	}
	testUser1 = &app.User{
		Active:     true,
		CreatedAt:  mustParseTime("1990-09-28T02:23:47.517Z"),
		ID:         uuid.New().String(),
		ModifiedAt: mustParseTime("2012-06-13T12:15:12.409Z"),
	}
	testUser2 = &app.User{
		Active:     true,
		CreatedAt:  mustParseTime("1963-06-20T18:13:56.452Z"),
		ID:         uuid.New().String(),
		ModifiedAt: mustParseTime("1973-11-03T20:20:24.775Z"),
	}
	testUsers       = []*app.User{testUser1, testUser2}
	testWashServer1 = &app.WashServer{
		CreatedAt:    mustParseTime("1975-05-01T01:06:58.866Z"),
		ID:           uuid.New().String(),
		Key:          "dolor",
		LastUpdateAt: mustParseTime("1930-12-07T09:46:48.156Z"),
		ModifiedAt:   mustParseTime("1933-03-12T12:13:43.559Z"),
		Name:         "ipsa",
	}
	testWashServer2 = &app.WashServer{
		CreatedAt:    mustParseTime("1945-12-18T18:37:10.108Z"),
		ID:           uuid.New().String(),
		Key:          "id",
		LastUpdateAt: mustParseTime("1986-08-11T00:12:04.260Z"),
		ModifiedAt:   mustParseTime("1950-12-26T15:42:47.528Z"),
		Name:         "quae",
	}
	testWashServers = []*app.WashServer{testWashServer1, testWashServer2}
	listParams      = &app.ListParams{
		Offset: 0,
		Limit:  5,
	}
)

func mustParseTime(t string) *time.Time {
	date, err := time.Parse(time.RFC3339, t)
	if err != nil {
		date, _ = time.Parse(strfmt.RFC3339FullDate, t)
	}
	return &date
}
