// Code generated by go-swagger; DO NOT EDIT.

package role

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"wash-bonus/internal/api/restapi/models"
)

// AddRoleCreatedCode is the HTTP code returned for type AddRoleCreated
const AddRoleCreatedCode int = 201

/*AddRoleCreated Created

swagger:response addRoleCreated
*/
type AddRoleCreated struct {

	/*
	  In: Body
	*/
	Payload *models.Role `json:"body,omitempty"`
}

// NewAddRoleCreated creates AddRoleCreated with default headers values
func NewAddRoleCreated() *AddRoleCreated {

	return &AddRoleCreated{}
}

// WithPayload adds the payload to the add role created response
func (o *AddRoleCreated) WithPayload(payload *models.Role) *AddRoleCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add role created response
func (o *AddRoleCreated) SetPayload(payload *models.Role) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddRoleCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*AddRoleDefault error

swagger:response addRoleDefault
*/
type AddRoleDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewAddRoleDefault creates AddRoleDefault with default headers values
func NewAddRoleDefault(code int) *AddRoleDefault {
	if code <= 0 {
		code = 500
	}

	return &AddRoleDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the add role default response
func (o *AddRoleDefault) WithStatusCode(code int) *AddRoleDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the add role default response
func (o *AddRoleDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the add role default response
func (o *AddRoleDefault) WithPayload(payload *models.Error) *AddRoleDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add role default response
func (o *AddRoleDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddRoleDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
