// Code generated by go-swagger; DO NOT EDIT.

package role

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DeleteRoleHandlerFunc turns a function with the right signature into a delete role handler
type DeleteRoleHandlerFunc func(DeleteRoleParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteRoleHandlerFunc) Handle(params DeleteRoleParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// DeleteRoleHandler interface for that can handle valid delete role params
type DeleteRoleHandler interface {
	Handle(DeleteRoleParams, interface{}) middleware.Responder
}

// NewDeleteRole creates a new http.Handler for the delete role operation
func NewDeleteRole(ctx *middleware.Context, handler DeleteRoleHandler) *DeleteRole {
	return &DeleteRole{Context: ctx, Handler: handler}
}

/* DeleteRole swagger:route DELETE /role/delete Role deleteRole

DeleteRole delete role API

*/
type DeleteRole struct {
	Context *middleware.Context
	Handler DeleteRoleHandler
}

func (o *DeleteRole) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteRoleParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// DeleteRoleBody delete role body
//
// swagger:model DeleteRoleBody
type DeleteRoleBody struct {

	// id
	ID string `json:"id,omitempty"`
}

// Validate validates this delete role body
func (o *DeleteRoleBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this delete role body based on context it is used
func (o *DeleteRoleBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DeleteRoleBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteRoleBody) UnmarshalBinary(b []byte) error {
	var res DeleteRoleBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
