// Code generated by go-swagger; DO NOT EDIT.

package wash_server

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"wash-bonus/internal/api/restapi/models"
)

// NewAddWashServerParams creates a new AddWashServerParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAddWashServerParams() *AddWashServerParams {
	return &AddWashServerParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAddWashServerParamsWithTimeout creates a new AddWashServerParams object
// with the ability to set a timeout on a request.
func NewAddWashServerParamsWithTimeout(timeout time.Duration) *AddWashServerParams {
	return &AddWashServerParams{
		timeout: timeout,
	}
}

// NewAddWashServerParamsWithContext creates a new AddWashServerParams object
// with the ability to set a context for a request.
func NewAddWashServerParamsWithContext(ctx context.Context) *AddWashServerParams {
	return &AddWashServerParams{
		Context: ctx,
	}
}

// NewAddWashServerParamsWithHTTPClient creates a new AddWashServerParams object
// with the ability to set a custom HTTPClient for a request.
func NewAddWashServerParamsWithHTTPClient(client *http.Client) *AddWashServerParams {
	return &AddWashServerParams{
		HTTPClient: client,
	}
}

/*
AddWashServerParams contains all the parameters to send to the API endpoint

	for the add wash server operation.

	Typically these are written to a http.Request.
*/
type AddWashServerParams struct {

	// Body.
	Body *models.WashServerAdd

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the add wash server params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddWashServerParams) WithDefaults() *AddWashServerParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the add wash server params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddWashServerParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the add wash server params
func (o *AddWashServerParams) WithTimeout(timeout time.Duration) *AddWashServerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add wash server params
func (o *AddWashServerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add wash server params
func (o *AddWashServerParams) WithContext(ctx context.Context) *AddWashServerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add wash server params
func (o *AddWashServerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add wash server params
func (o *AddWashServerParams) WithHTTPClient(client *http.Client) *AddWashServerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add wash server params
func (o *AddWashServerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the add wash server params
func (o *AddWashServerParams) WithBody(body *models.WashServerAdd) *AddWashServerParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the add wash server params
func (o *AddWashServerParams) SetBody(body *models.WashServerAdd) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *AddWashServerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
