// Code generated by go-swagger; DO NOT EDIT.

package wash_server

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"wash-bonus/internal/api/restapi/models"
)

// EditWashServerReader is a Reader for the EditWashServer structure.
type EditWashServerReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EditWashServerReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewEditWashServerOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewEditWashServerDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewEditWashServerOK creates a EditWashServerOK with default headers values
func NewEditWashServerOK() *EditWashServerOK {
	return &EditWashServerOK{}
}

/* EditWashServerOK describes a response with status code 200, with default header values.

OK
*/
type EditWashServerOK struct {
}

func (o *EditWashServerOK) Error() string {
	return fmt.Sprintf("[PUT /washServer/edit][%d] editWashServerOK ", 200)
}

func (o *EditWashServerOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewEditWashServerDefault creates a EditWashServerDefault with default headers values
func NewEditWashServerDefault(code int) *EditWashServerDefault {
	return &EditWashServerDefault{
		_statusCode: code,
	}
}

/* EditWashServerDefault describes a response with status code -1, with default header values.

error
*/
type EditWashServerDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the edit wash server default response
func (o *EditWashServerDefault) Code() int {
	return o._statusCode
}

func (o *EditWashServerDefault) Error() string {
	return fmt.Sprintf("[PUT /washServer/edit][%d] editWashServer default  %+v", o._statusCode, o.Payload)
}
func (o *EditWashServerDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *EditWashServerDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*EditWashServerBody edit wash server body
swagger:model EditWashServerBody
*/
type EditWashServerBody struct {

	// data
	Data *models.WashServerAdd `json:"data,omitempty"`

	// id
	ID string `json:"id,omitempty"`
}

// Validate validates this edit wash server body
func (o *EditWashServerBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *EditWashServerBody) validateData(formats strfmt.Registry) error {
	if swag.IsZero(o.Data) { // not required
		return nil
	}

	if o.Data != nil {
		if err := o.Data.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("body" + "." + "data")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("body" + "." + "data")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this edit wash server body based on the context it is used
func (o *EditWashServerBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *EditWashServerBody) contextValidateData(ctx context.Context, formats strfmt.Registry) error {

	if o.Data != nil {
		if err := o.Data.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("body" + "." + "data")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("body" + "." + "data")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *EditWashServerBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *EditWashServerBody) UnmarshalBinary(b []byte) error {
	var res EditWashServerBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
