// Code generated by go-swagger; DO NOT EDIT.

package wash_server

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"wash-bonus/internal/api/restapi/models"
)

// ListWashServerReader is a Reader for the ListWashServer structure.
type ListWashServerReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListWashServerReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListWashServerOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewListWashServerDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewListWashServerOK creates a ListWashServerOK with default headers values
func NewListWashServerOK() *ListWashServerOK {
	return &ListWashServerOK{}
}

/* ListWashServerOK describes a response with status code 200, with default header values.

OK
*/
type ListWashServerOK struct {
	Payload *ListWashServerOKBody
}

func (o *ListWashServerOK) Error() string {
	return fmt.Sprintf("[POST /washServer/list][%d] listWashServerOK  %+v", 200, o.Payload)
}
func (o *ListWashServerOK) GetPayload() *ListWashServerOKBody {
	return o.Payload
}

func (o *ListWashServerOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(ListWashServerOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListWashServerDefault creates a ListWashServerDefault with default headers values
func NewListWashServerDefault(code int) *ListWashServerDefault {
	return &ListWashServerDefault{
		_statusCode: code,
	}
}

/* ListWashServerDefault describes a response with status code -1, with default header values.

error
*/
type ListWashServerDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the list wash server default response
func (o *ListWashServerDefault) Code() int {
	return o._statusCode
}

func (o *ListWashServerDefault) Error() string {
	return fmt.Sprintf("[POST /washServer/list][%d] listWashServer default  %+v", o._statusCode, o.Payload)
}
func (o *ListWashServerDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *ListWashServerDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*ListWashServerOKBody list wash server o k body
swagger:model ListWashServerOKBody
*/
type ListWashServerOKBody struct {

	// items
	Items []*models.WashServer `json:"items"`

	// warnings
	Warnings []string `json:"warnings"`
}

// Validate validates this list wash server o k body
func (o *ListWashServerOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateItems(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ListWashServerOKBody) validateItems(formats strfmt.Registry) error {
	if swag.IsZero(o.Items) { // not required
		return nil
	}

	for i := 0; i < len(o.Items); i++ {
		if swag.IsZero(o.Items[i]) { // not required
			continue
		}

		if o.Items[i] != nil {
			if err := o.Items[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("listWashServerOK" + "." + "items" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("listWashServerOK" + "." + "items" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this list wash server o k body based on the context it is used
func (o *ListWashServerOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateItems(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ListWashServerOKBody) contextValidateItems(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Items); i++ {

		if o.Items[i] != nil {
			if err := o.Items[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("listWashServerOK" + "." + "items" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("listWashServerOK" + "." + "items" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *ListWashServerOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ListWashServerOKBody) UnmarshalBinary(b []byte) error {
	var res ListWashServerOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
