// Code generated by go-swagger; DO NOT EDIT.

package wash_server

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"wash-bonus/internal/api/restapi/models"
)

// ListWashServerReader is a Reader for the ListWashServer structure.
type ListWashServerReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListWashServerReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListWashServerOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewListWashServerDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewListWashServerOK creates a ListWashServerOK with default headers values
func NewListWashServerOK() *ListWashServerOK {
	return &ListWashServerOK{}
}

/* ListWashServerOK describes a response with status code 200, with default header values.

OK
*/
type ListWashServerOK struct {
	Payload *models.ListWashServer
}

func (o *ListWashServerOK) Error() string {
	return fmt.Sprintf("[POST /washServers/][%d] listWashServerOK  %+v", 200, o.Payload)
}
func (o *ListWashServerOK) GetPayload() *models.ListWashServer {
	return o.Payload
}

func (o *ListWashServerOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ListWashServer)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListWashServerDefault creates a ListWashServerDefault with default headers values
func NewListWashServerDefault(code int) *ListWashServerDefault {
	return &ListWashServerDefault{
		_statusCode: code,
	}
}

/* ListWashServerDefault describes a response with status code -1, with default header values.

error
*/
type ListWashServerDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the list wash server default response
func (o *ListWashServerDefault) Code() int {
	return o._statusCode
}

func (o *ListWashServerDefault) Error() string {
	return fmt.Sprintf("[POST /washServers/][%d] listWashServer default  %+v", o._statusCode, o.Payload)
}
func (o *ListWashServerDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *ListWashServerDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
